package Controller;

import Model.Connection.connectionToDB;
import Model.Entity.empEn;
import Model.Service.empServ;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sogand
 */
public class EmployeeAff extends javax.swing.JFrame {

    /**
     * Creates new form Controller.EmployeeAff
     */
    public EmployeeAff() {
        initComponents();
        table_update();
        setCal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        DeleteBut2 = new javax.swing.JButton();
        signoutBut2 = new javax.swing.JButton();
        addBut2 = new javax.swing.JButton();
        EditBut2 = new javax.swing.JButton();
        clearbut2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchbut = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        deptab = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        agetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emptxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fntxt = new javax.swing.JTextField();
        bsaltxt = new javax.swing.JTextField();
        namtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rolltxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        DeleteBut2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeleteBut2.setIcon(new javax.swing.ImageIcon("image/delete.png")); // NOI18N
        DeleteBut2.setText("Delete");
        DeleteBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBut2ActionPerformed(evt);
            }
        });

        signoutBut2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signoutBut2.setIcon(new javax.swing.ImageIcon("image/exit.png")); // NOI18N
        signoutBut2.setText("Signout");
        signoutBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBut2ActionPerformed(evt);
            }
        });

        addBut2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBut2.setIcon(new javax.swing.ImageIcon("image/plus.png")); // NOI18N
        addBut2.setText("Add");
        addBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBut2ActionPerformed(evt);
            }
        });

        EditBut2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EditBut2.setIcon(new javax.swing.ImageIcon("image/edit.png")); // NOI18N
        EditBut2.setText("Edit");
        EditBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBut2ActionPerformed(evt);
            }
        });

        clearbut2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearbut2.setIcon(new javax.swing.ImageIcon("image/garbage.png")); // NOI18N
        clearbut2.setText("Clear");
        clearbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearbut2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditBut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteBut2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(signoutBut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(addBut2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditBut2)
                .addGap(18, 18, 18)
                .addComponent(DeleteBut2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearbut2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signoutBut2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Employee Affiars");

        dateLab.setForeground(new java.awt.Color(255, 0, 51));
        dateLab.setIcon(new javax.swing.ImageIcon("image/calendar.png")); // NOI18N

        timelab.setForeground(new java.awt.Color(255, 0, 51));
        timelab.setIcon(new javax.swing.ImageIcon("image/time.png")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText(" Employee code");

        searchbut.setIcon(new javax.swing.ImageIcon("image/search.png")); // NOI18N
        searchbut.setText("search");
        searchbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(searchbut, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbut))
                .addContainerGap())
        );

        deptab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp Code", "Emp Name", "Age", "father's name", "Education", "Salary", "Roll", "Address", "PhoneNumber"
            }
        ));
        deptab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptabMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(deptab);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel5.setText("Age");

        jLabel6.setText("father's name");

        jLabel4.setText("Name");

        jLabel3.setText("Employe code");

        jLabel9.setText(" basic salary");

        jLabel7.setText("Level of education");

        jLabel10.setText("Roll");

        jLabel11.setText("Address");

        jLabel12.setText("PhoneNumber");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bsaltxt)
                    .addComponent(loetxt)
                    .addComponent(fntxt)
                    .addComponent(agetxt)
                    .addComponent(namtxt)
                    .addComponent(emptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(rolltxt)
                    .addComponent(addresstxt)
                    .addComponent(phonetxt))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(namtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rolltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timelab, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLab)
                    .addComponent(jLabel1)
                    .addComponent(timelab))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    PreparedStatement insert;
    ResultSet rs ;
    
        public void setCal(){
        Calendar cal = new GregorianCalendar();
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int hour = cal.get(Calendar.HOUR);
        int minute = cal.get(Calendar.MINUTE);
        int second = cal.get(Calendar.SECOND);
        dateLab.setText("Today's date : "+  day + " / " + (month + 1)+ " / "  + year);
        timelab.setText("Time : "+hour+" : "+minute+" : "+second);
       
        
    }
    
      private void table_update(){
          ResultSet rs;
        int c;
        try {

            rs= empServ.getInstance().select();
            ResultSetMetaData Rss=rs.getMetaData();
            c=Rss.getColumnCount();
            DefaultTableModel Df=(DefaultTableModel)deptab.getModel();
            Df.setRowCount(0);
            
            while(rs.next()){
                Vector v2=new Vector();
                
                for(int a=1;a<=c;a++){
                    v2.add(rs.getString("code"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("age"));
                    v2.add(rs.getString("fname"));
                    v2.add(rs.getString("education"));
                    v2.add(rs.getString("salary"));
                    v2.add(rs.getString("roll"));
                    v2.add(rs.getString("address"));
                    v2.add(rs.getString("phone"));
                    
                }
                
                Df.addRow(v2);   
            }
           
            }catch (SQLException ex) {
            Logger.getLogger(Document.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }


      }
    private void DeleteBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBut2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Df= (DefaultTableModel) deptab.getModel();
        int selectedIndex=deptab.getSelectedRow();
        String code=emptxt.getText();


        code=Df.getValueAt(selectedIndex, 0).toString();

        empEn empEn=new empEn();
        empEn.setCode(code);
        int dialogResult=JOptionPane.showConfirmDialog(null,"Do you want to delete the record?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){

            try {

                empServ.getInstance().delete(empEn);

                JOptionPane.showMessageDialog(this,"Record deleted");

                table_update();

                emptxt.setText("");
                namtxt.setText("");
                agetxt.setText("");
                fntxt.setText("");
                loetxt.setText("");
                bsaltxt.setText("");
                rolltxt.setText("");
                addresstxt.setText("");
                phonetxt.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeAff.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteBut2ActionPerformed

    private void signoutBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBut2ActionPerformed
        setVisible(false);
        LoginFrame s= new LoginFrame();
        s.setVisible(true);

    }//GEN-LAST:event_signoutBut2ActionPerformed

    private void addBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBut2ActionPerformed
        // TODO add your handling code here:

        String code=emptxt.getText();
        String name=namtxt.getText();
        String age=agetxt.getText();
        String father=fntxt.getText();
        String edu=loetxt.getText();
        String salary=bsaltxt.getText();
        String roll=rolltxt.getText();
        String address=addresstxt.getText();
        String phone=phonetxt.getText();

        empEn empEn=new empEn();
        empEn.setCode(code);
        empEn.setName(name);
        empEn.setAge(age);
        empEn.setFname(father);
        empEn.setEducation(edu);
        empEn.setSalary(salary);
        empEn.setRoll(roll);
        empEn.setAddress(address);
        empEn.setPhone(phone);
        try {

            empServ.getInstance().insert(empEn);

            JOptionPane.showMessageDialog(this,"Record Addedd");

            table_update();

            emptxt.setText("");
            namtxt.setText("");
            agetxt.setText("");
            fntxt.setText("");
            loetxt.setText("");
            bsaltxt.setText("");
            rolltxt.setText("");
            addresstxt.setText("");
            phonetxt.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(EmployeeAff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addBut2ActionPerformed

    private void EditBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBut2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df= (DefaultTableModel) deptab.getModel();
        int selectedIndex=deptab.getSelectedRow();
        String code=emptxt.getText();
        String name=namtxt.getText();
        String age=agetxt.getText();
        String father=fntxt.getText();
        String edu=loetxt.getText();
        String salary=bsaltxt.getText();
        String roll=rolltxt.getText();
        String address=addresstxt.getText();
        String phone=phonetxt.getText();


        empEn empEn=new empEn();
        empEn.setCode(code);
        empEn.setName(name);
        empEn.setAge(age);
        empEn.setFname(father);
        empEn.setEducation(edu);
        empEn.setSalary(salary);
        empEn.setRoll(roll);
        empEn.setAddress(address);
        empEn.setPhone(phone);

        try {

            empServ.getInstance().update(empEn);

            JOptionPane.showMessageDialog(this,"Record Updated");

            table_update();

           emptxt.setText("");
            namtxt.setText("");
            agetxt.setText("");
            fntxt.setText("");
            loetxt.setText("");
            bsaltxt.setText("");
            rolltxt.setText("");
            addresstxt.setText("");
            phonetxt.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(Document.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_EditBut2ActionPerformed

    private void clearbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbut2ActionPerformed
        // TODO add your handling code here:
         String code=emptxt.getText();
        String name=namtxt.getText();
        String age=agetxt.getText();
        String father=fntxt.getText();
        String edu=loetxt.getText();
        String salary=bsaltxt.getText();
        String roll=rolltxt.getText();
        String address=addresstxt.getText();
        String phone=phonetxt.getText();
        Connection conn=connectionToDB.ConectorDb();

        emptxt.setText("");
        namtxt.setText("");
        agetxt.setText("");
        fntxt.setText("");
        loetxt.setText("");
        bsaltxt.setText("");
        rolltxt.setText("");
        addresstxt.setText("");
        phonetxt.setText("");

    }//GEN-LAST:event_clearbut2ActionPerformed

    private void searchbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbutActionPerformed
        ResultSet rs;
        try {


            String code=searchField.getText();
            empEn empEn=new empEn();
            empEn.setCode(code);
            rs=empServ.getInstance().findByCode(empEn);
            if(rs.next()){
                String add1=rs.getString("code");
                emptxt.setText(add1);
                String add2=rs.getString("name");
                namtxt.setText(add2);
                String add3=rs.getString("age");
                agetxt.setText(add3);
                String add4=rs.getString("fname");
                fntxt.setText(add4);
                String add6=rs.getString("education");
                loetxt.setText(add6);
                String add7=rs.getString("salary");
                bsaltxt.setText(add7);
                String add8=rs.getString("roll");
                rolltxt.setText(add8);
                String add9=rs.getString("address");
                addresstxt.setText(add9);
                String add10=rs.getString("phone");
                phonetxt.setText(add10);

            }else{
                JOptionPane.showMessageDialog(this,"Not found");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Document.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchbutActionPerformed

    private void deptabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptabMouseClicked
        // TODO add your handling code here:

        DefaultTableModel Df= (DefaultTableModel) deptab.getModel();
        int selectedIndex=deptab.getSelectedRow();

        emptxt.setText(Df.getValueAt(selectedIndex, 0).toString());
        namtxt.setText(Df.getValueAt(selectedIndex, 1).toString());
        agetxt.setText(Df.getValueAt(selectedIndex, 2).toString());
        fntxt.setText(Df.getValueAt(selectedIndex, 3).toString());
        loetxt.setText(Df.getValueAt(selectedIndex, 4).toString());
        bsaltxt.setText(Df.getValueAt(selectedIndex, 5).toString());
        rolltxt.setText(Df.getValueAt(selectedIndex, 6).toString());
        addresstxt.setText(Df.getValueAt(selectedIndex, 7).toString());
        phonetxt.setText(Df.getValueAt(selectedIndex, 8).toString());
        
    }//GEN-LAST:event_deptabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBut;
    private javax.swing.JButton DeleteBut1;
    private javax.swing.JButton DeleteBut2;
    private javax.swing.JButton EditBut;
    private javax.swing.JButton EditBut1;
    private javax.swing.JButton EditBut2;
    private javax.swing.JButton addBut;
    private javax.swing.JButton addBut1;
    private javax.swing.JButton addBut2;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField bsaltxt;
    private javax.swing.JButton clearbut;
    private javax.swing.JButton clearbut1;
    private javax.swing.JButton clearbut2;
    private javax.swing.JLabel dateLab;
    private javax.swing.JTable deptab;
    private javax.swing.JTextField emptxt;
    private javax.swing.JTextField fntxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField loetxt;
    private javax.swing.JTextField namtxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JTextField rolltxt;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchbut;
    private javax.swing.JButton signoutBut;
    private javax.swing.JButton signoutBut1;
    private javax.swing.JButton signoutBut2;
    private javax.swing.JLabel timelab;
    // End of variables declaration//GEN-END:variables
}
